[workspace]
members = [
    "crates/csl_legacy",
    "crates/csln_core",
    "crates/csln_migrate",
    "crates/csln_processor",
    "crates/csln_analyze"
]
resolver = "2"

[workspace.lints.rust]
unsafe_code = "forbid"
