[package]
name = "csln_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "csln-cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
serde_json = "1.0"
schemars = "0.8"
csln_core = { path = "../csln_core" }
