[package]
name = "csl_legacy"
version.workspace = true
edition.workspace = true

[dependencies]
indexmap = "2.13.0"
roxmltree = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
