[package]
name = "csln_migrate"
version = "0.1.0"
edition = "2021"

[dependencies]
csl_legacy = { path = "../csl_legacy" }
csln_core = { path = "../csln_core" }
roxmltree = "0.20"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }